variables:
    immuta_version: 2022.1.3
    artifacts_bucket: immuta-ps-share
    driver_bucket: immuta-drivers
    immuta_trino_bucket: immuta-trino-image
    trino_version: 387
    helm_version: v3.9.0
    rke2_version: v1.23.7
    rke2_release: '%2Brke2r2'
    cli_version: v1.0.0

.build-immuta-trino: &trino
    image: alpine:latest
    script:
        - apk add --no-cache aws-cli buildah podman curl skopeo
        - aws s3 cp s3://$artifacts_bucket/immuta-${immuta_version}/immuta-trino.tar.gz .
        - id=$(buildah from trinodb/trino:$trino_version)
        - buildah add $id immuta-trino.tar.gz /usr/lib/trino/plugin/immuta
        - buildah commit $id registry.immuta.com/immuta/immuta-trino:$trino_version
        - podman save -o immuta-trino-$trino_version.tar registry.immuta.com/immuta/immuta-trino:$trino_version
        - aws s3 cp immuta-trino-$trino_version.tar s3://immuta-trino-image/
    when: manual

trino:387:
    variables:
        trino_version: 387
    <<: *trino

create_package:
    image: alpine:latest
    script:
      - apk add --no-cache aws-cli wget curl

      # Immuta files
      - cd roles/immuta/files
      - aws s3 cp s3://$driver_bucket/simbapresto-1.2.18.1019-1.el6.x86_64.rpm .
      - aws s3 cp s3://$driver_bucket/SimbaPrestoODBCDriver.lic .
      - aws s3 cp s3://$artifacts_bucket/immuta-${immuta_version}/immuta-${immuta_version}-all.tar.gz .
      - curl -Lo immuta https://immuta-platform-artifacts.s3.amazonaws.com/cli/${cli_version}/immuta_cli_linux_amd64
      - cd -

      # RKE2 files
      - cd roles/rke2/files
      - wget -q https://github.com/rancher/rke2/releases/download/${rke2_version}${rke2_release}/rke2-images.linux-amd64.tar.zst
      - wget -q https://github.com/rancher/rke2/releases/download/${rke2_version}${rke2_release}/rke2.linux-amd64.tar.gz
      - wget -q https://github.com/derailed/k9s/releases/download/v0.25.20/k9s_Linux_x86_64.tar.gz
      - wget -q https://get.helm.sh/helm-${helm_version}-linux-amd64.tar.gz
      - cd -

      # Trino files
      - cd roles/trino/files
      - wget -q https://repo1.maven.org/maven2/io/trino/trino-cli/$trino_version/trino-cli-$trino_version-executable.jar
      - aws s3 cp s3://$immuta_trino_bucket/immuta-trino-$trino_version.tar .
      - cd -

      - tar -zcv --exclude='.git*' -f immuta-$immuta_version-trino-$trino_version-rke2-$rke2_version.tar.gz .
      - ls -lh
      - aws s3 cp immuta-$immuta_version-trino-$trino_version-rke2-$rke2_version.tar.gz s3://immuta-rke2/
    when: manual
    artifacts:
        paths:
            - immuta-$immuta_version-trino-$trino_version-rke2-$rke2_version.tar.gz
