---
- name: Copy manifest to correct location
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/lib/rancher/rke2/server/manifests
    owner: root
    group: root
    mode: '0644'
  loop:
    - rke2-ingress-nginx.yaml
  when: enable_proxy
  tags:
      - post
